### PR TITLE
mmio: refine mmio region allocation

### PR DESCRIPTION
**Pull request by terenceli**
It is strange that device's mmio address beyond 4G. However,
this is current implementation. For example:

00:04.0 Unassigned class [ffff]: Red Hat, Inc. Virtio RNG
	Subsystem: Red Hat, Inc. Virtio RNG
	Flags: bus master, fast devsel, latency 0
	Memory at fffe00000 (64-bit, non-prefetchable) [size=512K]
	Capabilities: [40] Vendor Specific Information: VirtIO: CommonCfg
	Capabilities: [50] Vendor Specific Information: VirtIO: ISR
	Capabilities: [60] Vendor Specific Information: VirtIO: DeviceCfg
	Capabilities: [70] Vendor Specific Information: VirtIO: Notify
	Capabilities: [84] Vendor Specific Information: VirtIO: <unknown>
	Capabilities: [94] MSI-X: Enable+ Count=2 Masked-
	Kernel driver in use: virtio-pci

This is because we register all of the memory region in mmio address
space. This patch does mostly two things:

1. Change the mmio address space to 3G~3G+768M
2. don't register the memory region to mmio address space.

After this patch, lspci shows as follows:

00:04.0 Unassigned class [ffff]: Red Hat, Inc. Virtio RNG
	Subsystem: Red Hat, Inc. Virtio RNG
	Flags: bus master, fast devsel, latency 0
	Memory at efe00000 (64-bit, non-prefetchable) [size=512K]
	Capabilities: [40] Vendor Specific Information: VirtIO: CommonCfg
	Capabilities: [50] Vendor Specific Information: VirtIO: ISR
	Capabilities: [60] Vendor Specific Information: VirtIO: DeviceCfg
	Capabilities: [70] Vendor Specific Information: VirtIO: Notify
	Capabilities: [84] Vendor Specific Information: VirtIO: <unknown>
	Capabilities: [94] MSI-X: Enable+ Count=2 Masked-
	Kernel driver in use: virtio-pci

### CODE REVIEW

**Comment by sameo** [comment]
@terenceli Thanks a lot for your PR.
May I ask: Are there any concern with having that memory on 64 bits?

**Comment by sameo** [comment]
@terenceli @sboeuf We probably should document our memory model better, but placing the virtio memory bars at the end of the 64-bit address space was on purpose. We're only left with having to maintain a 32-bit hole for architecture specific bits (IOAPIC for example.

**Comment by terenceli** [comment]
@sameo in fact I don't think so. 


I made this change as following:


In the definition of 'MEM_32BIT_DEVICES_GAP_SIZE'

// We reserve 768MB in our memory gap for 32-bit devices (e.g. 32-bit PCI BARs).
const MEM_32BIT_DEVICES_GAP_SIZE: GuestUsize = (768 << 20);

IIUC the comment says the 3G~3G~768M is for devices' BAR.

Also in the 'Vm::new' functionl, why don't we have following code?

        // Allocate RAM and Reserved address ranges.
        for region in arch_mem_regions.iter() {
            allocator
                .allocate_mmio_addresses(Some(region.0), region.1 as GuestUsize, None)
                .ok_or(Error::MemoryRangeAllocation)?;
        }

'arch_mem_regions' contains the 'ram', why we allocate this in mmio address space.

Thanks,
Li Qiang

**Comment by sameo** [comment]
> @sameo in fact I don't think so.
> 
> I made this change as following:
> 
> In the definition of 'MEM_32BIT_DEVICES_GAP_SIZE'
> 
> // We reserve 768MB in our memory gap for 32-bit devices (e.g. 32-bit PCI BARs).
> const MEM_32BIT_DEVICES_GAP_SIZE: GuestUsize = (768 << 20);

That's accurate. We do reserve 768M for **32-bit** devices MMIO (e.g. PCI bars).  And 256M for architectural address (e.g. IOAPIC). The latter is architectural, i.e. we don't really have a choice. The former is only consumed to map 32-bit VFIO regions (We could map them into the 64-bit space as well, but for PCI devices, that consumes twice as much of the PCI config space and we would run out of space for devices with more than 3 bars). For virtio devices, we can decide where we want to put the BARs, and that can be anywhere after the 32-bit space. So placing virtio-pci BARs at the end of our address space (i.e. on 64-bit) was a purposely made decision for simplicity sake. 

> IIUC the comment says the 3G ~ 3G ~ 768M is for devices' BAR.
> 
> Also in the 'Vm::new' functionl, why do we have following code?
> 
> ```
>     // Allocate RAM and Reserved address ranges.
>     for region in arch_mem_regions.iter() {
>         allocator
>             .allocate_mmio_addresses(Some(region.0), region.1 as GuestUsize, None)
>             .ok_or(Error::MemoryRangeAllocation)?;
>     }
> ```
> 
> 'arch_mem_regions' contains the 'ram', why we allocate this in mmio address space.

`arch_mem_regions` contains all the RAM regions, but also the 32-bit hole (The whole 1G, 768+256)/ We call into `allocate_mmio` to reserve those region against our vm-allocator. That way additional devices (VFIO and virtio for example) will not get regions overlapping with neither RAM nor the 32-bit hole. We could keep RAM out of that and restrict the MMIO space to wherever RAM finishes but since there could be a hole in the RAM, looking at it from 0x0 makes it simpler to handle.   

> Another question, the mmio's size is just 1<<36, not 64G, typo or I missed anything?

I'm confused: How much is `1<<36` ?

**Comment by terenceli** [comment]
> > @sameo in fact I don't think so.
> > I made this change as following:
> > In the definition of 'MEM_32BIT_DEVICES_GAP_SIZE'
> > // We reserve 768MB in our memory gap for 32-bit devices (e.g. 32-bit PCI BARs).
> > const MEM_32BIT_DEVICES_GAP_SIZE: GuestUsize = (768 << 20);
> 
> That's accurate. We do reserve 768M for **32-bit** devices MMIO (e.g. PCI bars). And 256M for architectural address (e.g. IOAPIC). The latter is architectural, i.e. we don't really have a choice. The former is only consumed to map 32-bit VFIO regions (We could map them into the 64-bit space as well, but for PCI devices, that consumes twice as much of the PCI config space and we would run out of space for devices with more than 3 bars)

Sorry I can't understand why here need consumes twice as much of the PCI config space for VFIO device 


. For virtio devices, we can decide where we want to put the BARs, and that can be anywhere after the 32-bit space. So placing virtio-pci BARs at the end of our address space (i.e. on 64-bit) was a purposely made decision for simplicity sake.
> 
> > IIUC the comment says the 3G ~ 3G ~ 768M is for devices' BAR.
> > Also in the 'Vm::new' functionl, why do we have following code?
> > ```
> >     // Allocate RAM and Reserved address ranges.
> >     for region in arch_mem_regions.iter() {
> >         allocator
> >             .allocate_mmio_addresses(Some(region.0), region.1 as GuestUsize, None)
> >             .ok_or(Error::MemoryRangeAllocation)?;
> >     }
> > ```
> > 
> > 
> > 'arch_mem_regions' contains the 'ram', why we allocate this in mmio address space.
> 
> `arch_mem_regions` contains all the RAM regions, but also the 32-bit hole (The whole 1G, 768+256)/ We call into `allocate_mmio` to reserve those region against our vm-allocator. That way additional devices (VFIO and virtio for example) will not get regions overlapping with neither RAM nor the 32-bit hole. We could keep RAM out of that and restrict the MMIO space to wherever RAM finishes but since there could be a hole in the RAM, looking at it from 0x0 makes it simpler to handle.
> 
> > Another question, the mmio's size is just 1<<36, not 64G, typo or I missed anything?
> 
> I'm confused: How much is `1<<36` ?

Sorry, I'm confused with the 64-bits.

**Comment by sameo** [comment]
> > > @sameo in fact I don't think so.
> > > I made this change as following:
> > > In the definition of 'MEM_32BIT_DEVICES_GAP_SIZE'
> > > // We reserve 768MB in our memory gap for 32-bit devices (e.g. 32-bit PCI BARs).
> > > const MEM_32BIT_DEVICES_GAP_SIZE: GuestUsize = (768 << 20);
> > 
> > 
> > That's accurate. We do reserve 768M for **32-bit** devices MMIO (e.g. PCI bars). And 256M for architectural address (e.g. IOAPIC). The latter is architectural, i.e. we don't really have a choice. The former is only consumed to map 32-bit VFIO regions (We could map them into the 64-bit space as well, but for PCI devices, that consumes twice as much of the PCI config space and we would run out of space for devices with more than 3 bars)
> 
> Sorry I can't understand why here need consumes twice as much of the PCI config space for VFIO device
> 
The PCI config space has six (6) 32 bit registers for BARs. A 64-bit BAR consumes 2 of those. So at most you can have 3 64-bit BARs or 6 32-bit BARs, or a combination of the 2. So for example if a PCI device has 4 32-bit BARs then with VFIO we can't map that to 64-bit BARs on the guest, because there would not be enough space for 4 * 2 32-bit registers.
So with VFIO devices we decided to map 64-bit BARs to 64-bit guest BARs and 32-bit BARs to 32-bit guest BARs. The 32-bit BARs then force us to maintain a 32-bit PCI hole. 

For virtio, as none of the specified devices need more than 3 BARs, we can safely use 64-bit guest BARs and not worry about consuming a 32-bit PCI hole.

> > > Another question, the mmio's size is just 1<<36, not 64G, typo or I missed anything?
> > 
> > 
> > I'm confused: How much is `1<<36` ?
> 
> Sorry, I'm confused with the 64-bits.

Maybe I can try to clear the confusion: So using `1<<36` (which is 64 GB) as a size means we're restricting our guest to 64 GB addressable memory space, because that's how much some CPUs can physically address. Using something bigger and then placing the virtio devices at the end of that space mean that any virtio guest driver access would trigger a CPU fault as it may try to access unreachable memory.

**Comment by terenceli** [comment]
@sameo quite clear, Thanks. Will open this issue.

**Pull request closed without merging**
