### PR TITLE
tests: Use release build for integration tests

### PR DESCRIPTION
**Pull request by rbradford**
Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
Let's see if the test time changes...

**Comment by sboeuf** [comment]
@rbradford it took 30min

**Comment by rbradford** [comment]
Seems to make no difference on the time to run the integration tests.

**Comment by rbradford** [comment]
Reopening as we should really do our integration testing against the release build as that is what we are shipping to users.

**Pull request merged**
