### PR TITLE
[WIP]Rebase latest CrosVM VFIO patchset

### PR DESCRIPTION
**Pull request by chao-p**
Latest version of CrosVM VFIO patchset is available here:
https://chromium-review.googlesource.com/c/chromiumos/platform/crosvm/+/1580455

This PR rebases some of these patches to current cloud-hypervisor VFIO patchset.

### CODE REVIEW

**Comment by sameo** [comment]
@chao-p This has been merged into the topic/vfio branch (PR #60). Could you please check that it's all there, so that we can close that PR?

**Comment by chao-p** [comment]
> @chao-p This has been merged into the topic/vfio branch (PR #60). Could you please check that it's all there, so that we can close that PR?

Sounds all the code is there. Besides the code, there is another thing missing that is in my PR I actually checked and added some 'Signed-off-by' tags for both existing and new patches that we got from crosvm patchset. I believe we should keep the tag to follow the general open source rule. Does that make sense? @sameo

**Comment by sameo** [comment]
> > @chao-p This has been merged into the topic/vfio branch (PR #60). Could you please check that it's all there, so that we can close that PR?
> 
> Sounds all the code is there. Besides the code, there is another thing missing that is in my PR I actually checked and added some 'Signed-off-by' tags for both existing and new patches that we got from crosvm patchset. I believe we should keep the tag to follow the general open source rule. Does that make sense? @sameo

It absolutely makes sense. Which ones did I miss?

**Comment by chao-p** [comment]
> It absolutely makes sense. Which ones did I miss?

Should some existing patches, you can check my PR.

**Comment by sameo** [comment]
> > It absolutely makes sense. Which ones did I miss?
> 
> Should some existing patches, you can check my PR.

I went through all the patches and added the right SOBs.
The IRQ generalization one is a patch that is not coming from crosvm, but I added the SOBs you put there regardless.

**Comment by sameo** [comment]
> > > It absolutely makes sense. Which ones did I miss?
> > 
> > 
> > Should some existing patches, you can check my PR.
> 
> I went through all the patches and added the right SOBs.
> The IRQ generalization one is a patch that is not coming from crosvm, but I added the SOBs you put there regardless.

@chao-p Let me know if that looks better now.

**Comment by chao-p** [comment]
> > > > It absolutely makes sense. Which ones did I miss?
> > > 
> > > 
> > > Should some existing patches, you can check my PR.
> > 
> > 
> > I went through all the patches and added the right SOBs.
> > The IRQ generalization one is a patch that is not coming from crosvm, but I added the SOBs you put there regardless.
> 
> @chao-p Let me know if that looks better now.

@sameo Yes, perfect.

**Comment by sameo** [comment]
> > > > > It absolutely makes sense. Which ones did I miss?
> > > > 
> > > > 
> > > > Should some existing patches, you can check my PR.
> > > 
> > > 
> > > I went through all the patches and added the right SOBs.
> > > The IRQ generalization one is a patch that is not coming from crosvm, but I added the SOBs you put there regardless.
> > 
> > 
> > @chao-p Let me know if that looks better now.
> 
> @sameo Yes, perfect.

Thanks a lot @chao-p. Closing the PR now.

**Pull request closed without merging**
